language: node_js

node_js:
  - 11

install: npm install

before_script: npm run lint && npm test

script: npm run build

after_script: npm run deploy && echo "Successfully deployed branch $TRAVIS_BRANCH"
